---
title: "week2"
date: "2024-01-31"
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6

---
## Statistics on S&P returns
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

data = readRDS("data/wk2_stocks.rds")
cumu_returns = sum(data$SPY_returns)
# cumu_returns = 2.1833
avg_returns = mean(data$SPY_returns)
#avg_returns = 0.00037656
sd_returns = sd(data$SPY_returns)
#sd_returns = 0.012219
```

+ The cumulative returns of the S&P index during this period is `r round(cumu_returns,2)`%.
+ The average daily returns of the S&P index during this period is `r round(avg_returns,2)`%.
+ The standard deviation of the daily returns of the S&P index during this period is `r round(sd_returns,2)`%.

## S&P Prices
```{r message = FALSE}
library(ggplot2)

ggplot(data, aes(x = date, y = SPY_prices)) +
  geom_line()

```

## S&P Yearly Returns
```{r message = FALSE}
library(dplyr)
library(lubridate)

yearly = data %>% 
  mutate(year = year(date)) %>% 
  filter(year < 2024) %>% 
  group_by(year) %>% 
  summarise(yearly_returns = sum(SPY_returns)*100)

ggplot(yearly, aes(x=year, y=yearly_returns)) +
  geom_col()
```